In [4]:
import pandas as pd

In [16]:
# Load the provided Excel file
file_path = r"C:\Code\energy-demand-forecasting\docs\msn_codes_and_descriptions.xlsx"

# Skip additional rows to locate the start of the MSN data in the "MSN descriptions" sheet
msn_descriptions = pd.read_excel(file_path, sheet_name="MSN descriptions", header=None, skiprows=20)

# Display the first few rows to check the structure
msn_descriptions.head(10)

,0,1,2,3
0,NaN,ARTCV,Asphalt and road oil total expenditures,Million dollars
1,NaN,ARTXB,Asphalt and road oil total end-use consumption,Billion Btu
2,NaN,ARTXD,"Asphalt and road oil average price, all end-us...",Dollars per million Btu
3,NaN,ARTXP,Asphalt and road oil total end-use consumption,Thousand barrels
4,NaN,ARTXV,Asphalt and road oil total end-use expenditures,Million dollars
5,NaN,AVACB,Aviation gasoline consumed by the transportati...,Billion Btu
6,NaN,AVACD,Aviation gasoline price in the transportation ...,Dollars per million Btu
7,NaN,AVACP,Aviation gasoline consumed by the transportati...,Thousand barrels
8,NaN,AVACV,Aviation gasoline expenditures in the transpor...,Million dollars
9,NaN,AVTCB,Aviation gasoline total consumption,Billion Btu

In [17]:
# Rename the columns for clarity
msn_descriptions.columns = ["Index", "MSN", "Description", "Unit"]

# Drop unnecessary rows (e.g., empty rows)
msn_descriptions = msn_descriptions.dropna(subset=["MSN", "Description"])

# Filter MSN codes for nuclear-related terms
keywords = ["nuclear", "electric", "uranium", "generation"]
nuclear_msn = msn_descriptions[msn_descriptions['Description'].str.contains('|'.join(keywords), case=False, na=False)]

# Display nuclear-related MSN codes and descriptions
nuclear_msn.reset_index(drop=True, inplace=True)
nuclear_msn

,Index,MSN,Description,Unit
0,NaN,BTVHN,Battery electric vehicle (BEV) light-duty stocks,Thousands of registered vehicles
1,NaN,BTVHP,Electricity consumed for battery electric vehi...,Million kilowatthours
2,NaN,CLEIB,Coal consumed by the electric power sector,Billion Btu
3,NaN,CLEID,Coal price in the electric power sector,Dollars per million Btu
4,NaN,CLEIK,Factor for converting coal consumed by the ele...,Million Btu per short ton
...,...,...,...,...
140,NaN,WYEGB,Wind energy consumed for electricity generatio...,Billion Btu
141,NaN,WYEGP,Wind electricity net generation in the electri...,Million kilowatthours
142,NaN,WYICP,Wind electricity net generation in the industr...,Million kilowatthours
143,NaN,WYTCP,Wind electricity total net generation,Million kilowatthours
144,NaN,WYTXP,Wind energy total end-use net generation,Million kilowatthours

In [20]:
# Save the file to the specified path
specified_path = r"C:\Code\energy-demand-forecasting\docs\nuclear_related_msn_codes.csv"
nuclear_msn.to_csv(specified_path, index=False)

specified_path

'C:\\Code\\energy-demand-forecasting\\docs\\nuclear_related_msn_codes.csv'